### ISSUE TITLE
Upgrade to php 8.x

### ISSUE THREAD

**Issue by AlexanderMohan** [DiouxX/docker-glpi#82]
Php 7.4 is now unsupported. Please can this image be updated?

<img width="733" alt="2023-04-14 at 08 33 16 - Microsoft Edge@2x" src="https://user-images.githubusercontent.com/3938146/231975511-1853d3e1-7d3a-4759-a9e7-501934c6cd1b.png">

**Comment by DiouxX** [comment]
Hello,

Currently, php7.4 is officially and natively supported in the debian 11 repositories
Php8 will be natively for debian 12.x

![image](https://user-images.githubusercontent.com/11738556/232132285-f036562c-3748-4fba-8e2b-be866b8e9563.png)

However, php7.4 is no longer supported since the end of 2022

![image](https://user-images.githubusercontent.com/11738556/232132389-cc9bc82e-0b45-44a3-880e-26d9be82b6b1.png)


I will test the installation and validation of php8.x for GLPI

**Comment by DiouxX** [comment]
Hello,

I have updated the image to support PHP 8.1 to replace PHP 7.X which is no longer supported.

This is fixed with the following PR https://github.com/DiouxX/docker-glpi/pull/87
