### ISSUE TITLE
Use Azure Database for MariaDB server with diouxx/glpi

### ISSUE THREAD

**Issue by ljbili** [DiouxX/docker-glpi#92]
hello,

how can i use cloud managed database (in my case on Azure Database for MariaDB server) with docker image diouxx/glpi (installed on VM) ?

thanks for help,

Regards,

Lokmane.

**Comment by DiouxX** [comment]
Hi,

I only worked in Azure with Azure Database for MySQL - Flexible Server but I guess it's the same for MariaDB

So, you have several solutions:

- Either your VM has an IP address and then, you enter this IP address in the list of IPs that can connect to your MariaDB instance.
I advise you to activate the IP base filtering ;)

- Or you can use the VNet integration so that the communications between your VM and your MariaDB instance use the Microsoft backbone (https://learn.microsoft.com/en-us/azure/mariadb/howto-manage-vnet-portal)

**Comment by ljbili** [comment]
Thanks for your answer, the communication between VM and Database it's already OK, but i need to now how can i change docker-compose.yml for delete mariadb container and replace it with azure database.

Regards

**Comment by DiouxX** [comment]
Just remove the mariadb section from docker-compose.

With your configuration, you just need GLPI container running
